package common

const (
	AUTH_LOGIN   = "AUTH_LOGIN"
	AUTH_SIGNIN   = "AUTH_SIGNIN"
	AUTH_ERROR   = "AUTH_ERROR"
	AUTH_SUCCESS = "AUTH_SUCCESS"

	GAME_RECEIPT = "GAME_RECEIPT"
	GAME_CREATE = "GAME_CREATE"
	GAME_SELECT = "GAME_SELECT"
	GAME_ERROR = "GAME_ERROR"

	GAME_RECEIPT_PARTY = "GAME_RECEIPT_PARTY"
	GAME_RECEIPT_TIME  = "GAME_RECEIPT_TIME"
	GAME_RECEIPT_SCENE = "GAME_RECEIPT_SCENE"
	GAME_RECEIPT_BAG   = "GAME_RECEIPT_BAG"
	GAME_RECEIPT_MESSAGE = "GAME_RECEIPT_MESSAGE"
	GAME_RECEIPT_USER = "GAME_RECEIPT_USER"

	GAME_GET_PARTY = "GAME_GET_PARTY"
	GAME_GET_USER = "GAME_GET_USER"
	GAME_GET_TIME  = "GAME_GET_TIME"
	GAME_GET_SCENE = "GAME_GET_SCENE"
	GAME_GET_BAG   = "GAME_GET_BAG"

	GAME_HANDLE_CARD = "GAME_HANDLE_CARD"
	GAME_HANDLE_ITEM = "GAME_HANDLE_ITEM"
	GAME_HANDLE_TECH = "GAME_HANDLE_TECH"
)
